// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gosnake.proto

package comm // import "gosnake-server/comm"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Up struct {
	// Types that are valid to be assigned to M:
	//	*Up_Join
	//	*Up_Op
	M                    isUp_M   `protobuf_oneof:"m"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Up) Reset()         { *m = Up{} }
func (m *Up) String() string { return proto.CompactTextString(m) }
func (*Up) ProtoMessage()    {}
func (*Up) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_ba3910e5edc99de5, []int{0}
}
func (m *Up) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Up.Unmarshal(m, b)
}
func (m *Up) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Up.Marshal(b, m, deterministic)
}
func (dst *Up) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Up.Merge(dst, src)
}
func (m *Up) XXX_Size() int {
	return xxx_messageInfo_Up.Size(m)
}
func (m *Up) XXX_DiscardUnknown() {
	xxx_messageInfo_Up.DiscardUnknown(m)
}

var xxx_messageInfo_Up proto.InternalMessageInfo

type isUp_M interface {
	isUp_M()
}

type Up_Join struct {
	Join *Up_UpJoin `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type Up_Op struct {
	Op *Up_UpOp `protobuf:"bytes,2,opt,name=op,proto3,oneof"`
}

func (*Up_Join) isUp_M() {}

func (*Up_Op) isUp_M() {}

func (m *Up) GetM() isUp_M {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *Up) GetJoin() *Up_UpJoin {
	if x, ok := m.GetM().(*Up_Join); ok {
		return x.Join
	}
	return nil
}

func (m *Up) GetOp() *Up_UpOp {
	if x, ok := m.GetM().(*Up_Op); ok {
		return x.Op
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Up) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Up_OneofMarshaler, _Up_OneofUnmarshaler, _Up_OneofSizer, []interface{}{
		(*Up_Join)(nil),
		(*Up_Op)(nil),
	}
}

func _Up_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Up)
	// m
	switch x := m.M.(type) {
	case *Up_Join:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Join); err != nil {
			return err
		}
	case *Up_Op:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Op); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Up.M has unexpected type %T", x)
	}
	return nil
}

func _Up_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Up)
	switch tag {
	case 1: // m.join
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Up_UpJoin)
		err := b.DecodeMessage(msg)
		m.M = &Up_Join{msg}
		return true, err
	case 2: // m.op
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Up_UpOp)
		err := b.DecodeMessage(msg)
		m.M = &Up_Op{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Up_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Up)
	// m
	switch x := m.M.(type) {
	case *Up_Join:
		s := proto.Size(x.Join)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Up_Op:
		s := proto.Size(x.Op)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Up_UpJoin struct {
	Mode                 int32    `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Up_UpJoin) Reset()         { *m = Up_UpJoin{} }
func (m *Up_UpJoin) String() string { return proto.CompactTextString(m) }
func (*Up_UpJoin) ProtoMessage()    {}
func (*Up_UpJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_ba3910e5edc99de5, []int{0, 0}
}
func (m *Up_UpJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Up_UpJoin.Unmarshal(m, b)
}
func (m *Up_UpJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Up_UpJoin.Marshal(b, m, deterministic)
}
func (dst *Up_UpJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Up_UpJoin.Merge(dst, src)
}
func (m *Up_UpJoin) XXX_Size() int {
	return xxx_messageInfo_Up_UpJoin.Size(m)
}
func (m *Up_UpJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_Up_UpJoin.DiscardUnknown(m)
}

var xxx_messageInfo_Up_UpJoin proto.InternalMessageInfo

func (m *Up_UpJoin) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type Up_UpOp struct {
	Keycode              int32    `protobuf:"varint,1,opt,name=keycode,proto3" json:"keycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Up_UpOp) Reset()         { *m = Up_UpOp{} }
func (m *Up_UpOp) String() string { return proto.CompactTextString(m) }
func (*Up_UpOp) ProtoMessage()    {}
func (*Up_UpOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_ba3910e5edc99de5, []int{0, 1}
}
func (m *Up_UpOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Up_UpOp.Unmarshal(m, b)
}
func (m *Up_UpOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Up_UpOp.Marshal(b, m, deterministic)
}
func (dst *Up_UpOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Up_UpOp.Merge(dst, src)
}
func (m *Up_UpOp) XXX_Size() int {
	return xxx_messageInfo_Up_UpOp.Size(m)
}
func (m *Up_UpOp) XXX_DiscardUnknown() {
	xxx_messageInfo_Up_UpOp.DiscardUnknown(m)
}

var xxx_messageInfo_Up_UpOp proto.InternalMessageInfo

func (m *Up_UpOp) GetKeycode() int32 {
	if m != nil {
		return m.Keycode
	}
	return 0
}

type Down struct {
	// Types that are valid to be assigned to M:
	//	*Down_Kickoff
	//	*Down_Frame
	//	*Down_Finish
	M                    isDown_M `protobuf_oneof:"m"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Down) Reset()         { *m = Down{} }
func (m *Down) String() string { return proto.CompactTextString(m) }
func (*Down) ProtoMessage()    {}
func (*Down) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_ba3910e5edc99de5, []int{1}
}
func (m *Down) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Down.Unmarshal(m, b)
}
func (m *Down) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Down.Marshal(b, m, deterministic)
}
func (dst *Down) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Down.Merge(dst, src)
}
func (m *Down) XXX_Size() int {
	return xxx_messageInfo_Down.Size(m)
}
func (m *Down) XXX_DiscardUnknown() {
	xxx_messageInfo_Down.DiscardUnknown(m)
}

var xxx_messageInfo_Down proto.InternalMessageInfo

type isDown_M interface {
	isDown_M()
}

type Down_Kickoff struct {
	Kickoff *Down_DownKickOff `protobuf:"bytes,1,opt,name=kickoff,proto3,oneof"`
}

type Down_Frame struct {
	Frame *Down_DownFrame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

type Down_Finish struct {
	Finish *Down_DownFinish `protobuf:"bytes,3,opt,name=finish,proto3,oneof"`
}

func (*Down_Kickoff) isDown_M() {}

func (*Down_Frame) isDown_M() {}

func (*Down_Finish) isDown_M() {}

func (m *Down) GetM() isDown_M {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *Down) GetKickoff() *Down_DownKickOff {
	if x, ok := m.GetM().(*Down_Kickoff); ok {
		return x.Kickoff
	}
	return nil
}

func (m *Down) GetFrame() *Down_DownFrame {
	if x, ok := m.GetM().(*Down_Frame); ok {
		return x.Frame
	}
	return nil
}

func (m *Down) GetFinish() *Down_DownFinish {
	if x, ok := m.GetM().(*Down_Finish); ok {
		return x.Finish
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Down) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Down_OneofMarshaler, _Down_OneofUnmarshaler, _Down_OneofSizer, []interface{}{
		(*Down_Kickoff)(nil),
		(*Down_Frame)(nil),
		(*Down_Finish)(nil),
	}
}

func _Down_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Down)
	// m
	switch x := m.M.(type) {
	case *Down_Kickoff:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Kickoff); err != nil {
			return err
		}
	case *Down_Frame:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Frame); err != nil {
			return err
		}
	case *Down_Finish:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Finish); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Down.M has unexpected type %T", x)
	}
	return nil
}

func _Down_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Down)
	switch tag {
	case 1: // m.kickoff
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Down_DownKickOff)
		err := b.DecodeMessage(msg)
		m.M = &Down_Kickoff{msg}
		return true, err
	case 2: // m.frame
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Down_DownFrame)
		err := b.DecodeMessage(msg)
		m.M = &Down_Frame{msg}
		return true, err
	case 3: // m.finish
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Down_DownFinish)
		err := b.DecodeMessage(msg)
		m.M = &Down_Finish{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Down_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Down)
	// m
	switch x := m.M.(type) {
	case *Down_Kickoff:
		s := proto.Size(x.Kickoff)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Down_Frame:
		s := proto.Size(x.Frame)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Down_Finish:
		s := proto.Size(x.Finish)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Down_Snake struct {
	Body                 []int32  `protobuf:"varint,1,rep,packed,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Down_Snake) Reset()         { *m = Down_Snake{} }
func (m *Down_Snake) String() string { return proto.CompactTextString(m) }
func (*Down_Snake) ProtoMessage()    {}
func (*Down_Snake) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_ba3910e5edc99de5, []int{1, 0}
}
func (m *Down_Snake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Down_Snake.Unmarshal(m, b)
}
func (m *Down_Snake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Down_Snake.Marshal(b, m, deterministic)
}
func (dst *Down_Snake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Down_Snake.Merge(dst, src)
}
func (m *Down_Snake) XXX_Size() int {
	return xxx_messageInfo_Down_Snake.Size(m)
}
func (m *Down_Snake) XXX_DiscardUnknown() {
	xxx_messageInfo_Down_Snake.DiscardUnknown(m)
}

var xxx_messageInfo_Down_Snake proto.InternalMessageInfo

func (m *Down_Snake) GetBody() []int32 {
	if m != nil {
		return m.Body
	}
	return nil
}

type Down_DownKickOff struct {
	Cid                  int32         `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Foods                []int32       `protobuf:"varint,2,rep,packed,name=foods,proto3" json:"foods,omitempty"`
	Snakes               []*Down_Snake `protobuf:"bytes,3,rep,name=snakes,proto3" json:"snakes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Down_DownKickOff) Reset()         { *m = Down_DownKickOff{} }
func (m *Down_DownKickOff) String() string { return proto.CompactTextString(m) }
func (*Down_DownKickOff) ProtoMessage()    {}
func (*Down_DownKickOff) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_ba3910e5edc99de5, []int{1, 1}
}
func (m *Down_DownKickOff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Down_DownKickOff.Unmarshal(m, b)
}
func (m *Down_DownKickOff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Down_DownKickOff.Marshal(b, m, deterministic)
}
func (dst *Down_DownKickOff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Down_DownKickOff.Merge(dst, src)
}
func (m *Down_DownKickOff) XXX_Size() int {
	return xxx_messageInfo_Down_DownKickOff.Size(m)
}
func (m *Down_DownKickOff) XXX_DiscardUnknown() {
	xxx_messageInfo_Down_DownKickOff.DiscardUnknown(m)
}

var xxx_messageInfo_Down_DownKickOff proto.InternalMessageInfo

func (m *Down_DownKickOff) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *Down_DownKickOff) GetFoods() []int32 {
	if m != nil {
		return m.Foods
	}
	return nil
}

func (m *Down_DownKickOff) GetSnakes() []*Down_Snake {
	if m != nil {
		return m.Snakes
	}
	return nil
}

type Down_DownFrame struct {
	Foods                []int32  `protobuf:"varint,1,rep,packed,name=foods,proto3" json:"foods,omitempty"`
	Keycodes             []int32  `protobuf:"varint,2,rep,packed,name=keycodes,proto3" json:"keycodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Down_DownFrame) Reset()         { *m = Down_DownFrame{} }
func (m *Down_DownFrame) String() string { return proto.CompactTextString(m) }
func (*Down_DownFrame) ProtoMessage()    {}
func (*Down_DownFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_ba3910e5edc99de5, []int{1, 2}
}
func (m *Down_DownFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Down_DownFrame.Unmarshal(m, b)
}
func (m *Down_DownFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Down_DownFrame.Marshal(b, m, deterministic)
}
func (dst *Down_DownFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Down_DownFrame.Merge(dst, src)
}
func (m *Down_DownFrame) XXX_Size() int {
	return xxx_messageInfo_Down_DownFrame.Size(m)
}
func (m *Down_DownFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_Down_DownFrame.DiscardUnknown(m)
}

var xxx_messageInfo_Down_DownFrame proto.InternalMessageInfo

func (m *Down_DownFrame) GetFoods() []int32 {
	if m != nil {
		return m.Foods
	}
	return nil
}

func (m *Down_DownFrame) GetKeycodes() []int32 {
	if m != nil {
		return m.Keycodes
	}
	return nil
}

type Down_DownFinish struct {
	Winer                int32    `protobuf:"varint,1,opt,name=winer,proto3" json:"winer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Down_DownFinish) Reset()         { *m = Down_DownFinish{} }
func (m *Down_DownFinish) String() string { return proto.CompactTextString(m) }
func (*Down_DownFinish) ProtoMessage()    {}
func (*Down_DownFinish) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_ba3910e5edc99de5, []int{1, 3}
}
func (m *Down_DownFinish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Down_DownFinish.Unmarshal(m, b)
}
func (m *Down_DownFinish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Down_DownFinish.Marshal(b, m, deterministic)
}
func (dst *Down_DownFinish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Down_DownFinish.Merge(dst, src)
}
func (m *Down_DownFinish) XXX_Size() int {
	return xxx_messageInfo_Down_DownFinish.Size(m)
}
func (m *Down_DownFinish) XXX_DiscardUnknown() {
	xxx_messageInfo_Down_DownFinish.DiscardUnknown(m)
}

var xxx_messageInfo_Down_DownFinish proto.InternalMessageInfo

func (m *Down_DownFinish) GetWiner() int32 {
	if m != nil {
		return m.Winer
	}
	return 0
}

func init() {
	proto.RegisterType((*Up)(nil), "comm.Up")
	proto.RegisterType((*Up_UpJoin)(nil), "comm.Up.UpJoin")
	proto.RegisterType((*Up_UpOp)(nil), "comm.Up.UpOp")
	proto.RegisterType((*Down)(nil), "comm.Down")
	proto.RegisterType((*Down_Snake)(nil), "comm.Down.Snake")
	proto.RegisterType((*Down_DownKickOff)(nil), "comm.Down.DownKickOff")
	proto.RegisterType((*Down_DownFrame)(nil), "comm.Down.DownFrame")
	proto.RegisterType((*Down_DownFinish)(nil), "comm.Down.DownFinish")
}

func init() { proto.RegisterFile("gosnake.proto", fileDescriptor_gosnake_ba3910e5edc99de5) }

var fileDescriptor_gosnake_ba3910e5edc99de5 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0xcd, 0x77, 0xdf, 0xbb, 0xa5, 0xbc, 0x32, 0xaf, 0x95, 0x10, 0x05, 0x43, 0x41, 0xe8, 0x42,
	0x53, 0xa8, 0x6b, 0x37, 0x45, 0x24, 0xe8, 0xa2, 0x30, 0xd2, 0x8d, 0x1b, 0x69, 0x93, 0x19, 0x1d,
	0x43, 0x72, 0x87, 0x44, 0x2c, 0xfd, 0x19, 0xfe, 0x62, 0x65, 0x26, 0xd3, 0x36, 0x74, 0x33, 0xdc,
	0xcb, 0x39, 0xe7, 0xde, 0x73, 0x66, 0x06, 0x06, 0x6f, 0xd8, 0x54, 0xeb, 0x82, 0x25, 0xb2, 0xc6,
	0x4f, 0x24, 0x5e, 0x86, 0x65, 0x39, 0xf9, 0xb6, 0xc1, 0x59, 0x49, 0x72, 0x05, 0xde, 0x07, 0x8a,
	0x2a, 0xb4, 0x63, 0x7b, 0xda, 0x9f, 0xff, 0x4b, 0x14, 0x96, 0xac, 0x64, 0xb2, 0x92, 0x8f, 0x28,
	0xaa, 0xd4, 0xa2, 0x1a, 0x26, 0x97, 0xe0, 0xa0, 0x0c, 0x1d, 0x4d, 0x1a, 0x74, 0x48, 0x4b, 0x99,
	0x5a, 0xd4, 0x41, 0x19, 0x5d, 0x40, 0xd0, 0x4a, 0x08, 0x01, 0xaf, 0xc4, 0x9c, 0xe9, 0x89, 0x3e,
	0xd5, 0x75, 0x14, 0x83, 0xa7, 0xb8, 0x24, 0x84, 0x5e, 0xc1, 0x76, 0xd9, 0x11, 0xde, 0xb7, 0x0b,
	0x17, 0xec, 0x72, 0xf2, 0xe3, 0x80, 0x77, 0x8f, 0xdb, 0x8a, 0xcc, 0xa1, 0x57, 0x88, 0xac, 0x40,
	0xce, 0x8d, 0xb1, 0xb3, 0x76, 0xa7, 0x02, 0xf5, 0xf1, 0x24, 0xb2, 0x62, 0xc9, 0x79, 0x6a, 0xd1,
	0x3d, 0x91, 0x5c, 0x83, 0xcf, 0xeb, 0x75, 0xc9, 0x8c, 0xcb, 0xd1, 0x89, 0xe2, 0x41, 0x61, 0xa9,
	0x45, 0x5b, 0x12, 0x99, 0x41, 0xc0, 0x45, 0x25, 0x9a, 0xf7, 0xd0, 0xd5, 0xf4, 0xf1, 0x29, 0x5d,
	0x83, 0xa9, 0x45, 0x0d, 0x2d, 0x3a, 0x07, 0xff, 0x59, 0x5d, 0xa2, 0xca, 0xb7, 0xc1, 0x7c, 0x17,
	0xda, 0xb1, 0xab, 0xf2, 0xa9, 0x3a, 0x7a, 0x85, 0x7e, 0xc7, 0x15, 0x19, 0x82, 0x9b, 0x89, 0xdc,
	0x44, 0x54, 0x25, 0x19, 0x81, 0xcf, 0x11, 0xf3, 0x26, 0x74, 0xb4, 0xaa, 0x6d, 0xc8, 0x14, 0x02,
	0xfd, 0x30, 0x4d, 0xe8, 0xc6, 0xee, 0xb4, 0x3f, 0x1f, 0x76, 0x4c, 0xe8, 0x65, 0xd4, 0xe0, 0xd1,
	0x1d, 0xfc, 0x3d, 0x84, 0x38, 0x0e, 0xb3, 0xbb, 0xc3, 0x22, 0xf8, 0x63, 0x2e, 0x73, 0xbf, 0xe5,
	0xd0, 0x47, 0x13, 0x80, 0x63, 0x28, 0xa5, 0xdf, 0x8a, 0x8a, 0xd5, 0xc6, 0x60, 0xdb, 0xe8, 0x17,
	0x58, 0x8c, 0x5f, 0xfe, 0x9b, 0xcf, 0x72, 0xd3, 0xb0, 0xfa, 0x8b, 0xd5, 0x33, 0xe5, 0x68, 0x13,
	0xe8, 0x9f, 0x73, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x16, 0xfe, 0x36, 0xa1, 0x4a, 0x02, 0x00,
	0x00,
}
