// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gosnake.proto

package comm // import "gosnake-server/comm"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mode int32

const (
	Mode_None Mode = 0
	Mode_P1P  Mode = 1
	Mode_P2P  Mode = 2
	Mode_P3P  Mode = 3
)

var Mode_name = map[int32]string{
	0: "None",
	1: "P1P",
	2: "P2P",
	3: "P3P",
}
var Mode_value = map[string]int32{
	"None": 0,
	"P1P":  1,
	"P2P":  2,
	"P3P":  3,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}
func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_db5d93a88d7ba5ba, []int{0}
}

type KeyCode int32

const (
	KeyCode_NO_KEY KeyCode = 0
	KeyCode_LEFT   KeyCode = -1
	KeyCode_UP     KeyCode = -20
	KeyCode_RIGHT  KeyCode = 1
	KeyCode_DOWN   KeyCode = 20
)

var KeyCode_name = map[int32]string{
	0:   "NO_KEY",
	-1:  "LEFT",
	-20: "UP",
	1:   "RIGHT",
	20:  "DOWN",
}
var KeyCode_value = map[string]int32{
	"NO_KEY": 0,
	"LEFT":   -1,
	"UP":     -20,
	"RIGHT":  1,
	"DOWN":   20,
}

func (x KeyCode) String() string {
	return proto.EnumName(KeyCode_name, int32(x))
}
func (KeyCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_db5d93a88d7ba5ba, []int{1}
}

type Up struct {
	// Types that are valid to be assigned to M:
	//	*Up_Join
	//	*Up_Op
	M                    isUp_M   `protobuf_oneof:"m"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Up) Reset()         { *m = Up{} }
func (m *Up) String() string { return proto.CompactTextString(m) }
func (*Up) ProtoMessage()    {}
func (*Up) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_db5d93a88d7ba5ba, []int{0}
}
func (m *Up) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Up.Unmarshal(m, b)
}
func (m *Up) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Up.Marshal(b, m, deterministic)
}
func (dst *Up) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Up.Merge(dst, src)
}
func (m *Up) XXX_Size() int {
	return xxx_messageInfo_Up.Size(m)
}
func (m *Up) XXX_DiscardUnknown() {
	xxx_messageInfo_Up.DiscardUnknown(m)
}

var xxx_messageInfo_Up proto.InternalMessageInfo

type isUp_M interface {
	isUp_M()
}

type Up_Join struct {
	Join *Up_UpJoin `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type Up_Op struct {
	Op *Up_UpOp `protobuf:"bytes,2,opt,name=op,proto3,oneof"`
}

func (*Up_Join) isUp_M() {}

func (*Up_Op) isUp_M() {}

func (m *Up) GetM() isUp_M {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *Up) GetJoin() *Up_UpJoin {
	if x, ok := m.GetM().(*Up_Join); ok {
		return x.Join
	}
	return nil
}

func (m *Up) GetOp() *Up_UpOp {
	if x, ok := m.GetM().(*Up_Op); ok {
		return x.Op
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Up) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Up_OneofMarshaler, _Up_OneofUnmarshaler, _Up_OneofSizer, []interface{}{
		(*Up_Join)(nil),
		(*Up_Op)(nil),
	}
}

func _Up_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Up)
	// m
	switch x := m.M.(type) {
	case *Up_Join:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Join); err != nil {
			return err
		}
	case *Up_Op:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Op); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Up.M has unexpected type %T", x)
	}
	return nil
}

func _Up_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Up)
	switch tag {
	case 1: // m.join
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Up_UpJoin)
		err := b.DecodeMessage(msg)
		m.M = &Up_Join{msg}
		return true, err
	case 2: // m.op
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Up_UpOp)
		err := b.DecodeMessage(msg)
		m.M = &Up_Op{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Up_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Up)
	// m
	switch x := m.M.(type) {
	case *Up_Join:
		s := proto.Size(x.Join)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Up_Op:
		s := proto.Size(x.Op)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Up_UpJoin struct {
	Mode                 Mode     `protobuf:"varint,1,opt,name=mode,proto3,enum=comm.Mode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Up_UpJoin) Reset()         { *m = Up_UpJoin{} }
func (m *Up_UpJoin) String() string { return proto.CompactTextString(m) }
func (*Up_UpJoin) ProtoMessage()    {}
func (*Up_UpJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_db5d93a88d7ba5ba, []int{0, 0}
}
func (m *Up_UpJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Up_UpJoin.Unmarshal(m, b)
}
func (m *Up_UpJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Up_UpJoin.Marshal(b, m, deterministic)
}
func (dst *Up_UpJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Up_UpJoin.Merge(dst, src)
}
func (m *Up_UpJoin) XXX_Size() int {
	return xxx_messageInfo_Up_UpJoin.Size(m)
}
func (m *Up_UpJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_Up_UpJoin.DiscardUnknown(m)
}

var xxx_messageInfo_Up_UpJoin proto.InternalMessageInfo

func (m *Up_UpJoin) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_None
}

type Up_UpOp struct {
	Keycode              KeyCode  `protobuf:"varint,1,opt,name=keycode,proto3,enum=comm.KeyCode" json:"keycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Up_UpOp) Reset()         { *m = Up_UpOp{} }
func (m *Up_UpOp) String() string { return proto.CompactTextString(m) }
func (*Up_UpOp) ProtoMessage()    {}
func (*Up_UpOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_db5d93a88d7ba5ba, []int{0, 1}
}
func (m *Up_UpOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Up_UpOp.Unmarshal(m, b)
}
func (m *Up_UpOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Up_UpOp.Marshal(b, m, deterministic)
}
func (dst *Up_UpOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Up_UpOp.Merge(dst, src)
}
func (m *Up_UpOp) XXX_Size() int {
	return xxx_messageInfo_Up_UpOp.Size(m)
}
func (m *Up_UpOp) XXX_DiscardUnknown() {
	xxx_messageInfo_Up_UpOp.DiscardUnknown(m)
}

var xxx_messageInfo_Up_UpOp proto.InternalMessageInfo

func (m *Up_UpOp) GetKeycode() KeyCode {
	if m != nil {
		return m.Keycode
	}
	return KeyCode_NO_KEY
}

type Down struct {
	// Types that are valid to be assigned to M:
	//	*Down_Kickoff
	//	*Down_Frame
	M                    isDown_M `protobuf_oneof:"m"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Down) Reset()         { *m = Down{} }
func (m *Down) String() string { return proto.CompactTextString(m) }
func (*Down) ProtoMessage()    {}
func (*Down) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_db5d93a88d7ba5ba, []int{1}
}
func (m *Down) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Down.Unmarshal(m, b)
}
func (m *Down) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Down.Marshal(b, m, deterministic)
}
func (dst *Down) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Down.Merge(dst, src)
}
func (m *Down) XXX_Size() int {
	return xxx_messageInfo_Down.Size(m)
}
func (m *Down) XXX_DiscardUnknown() {
	xxx_messageInfo_Down.DiscardUnknown(m)
}

var xxx_messageInfo_Down proto.InternalMessageInfo

type isDown_M interface {
	isDown_M()
}

type Down_Kickoff struct {
	Kickoff *Down_DownKickOff `protobuf:"bytes,1,opt,name=kickoff,proto3,oneof"`
}

type Down_Frame struct {
	Frame *Down_DownFrame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

func (*Down_Kickoff) isDown_M() {}

func (*Down_Frame) isDown_M() {}

func (m *Down) GetM() isDown_M {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *Down) GetKickoff() *Down_DownKickOff {
	if x, ok := m.GetM().(*Down_Kickoff); ok {
		return x.Kickoff
	}
	return nil
}

func (m *Down) GetFrame() *Down_DownFrame {
	if x, ok := m.GetM().(*Down_Frame); ok {
		return x.Frame
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Down) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Down_OneofMarshaler, _Down_OneofUnmarshaler, _Down_OneofSizer, []interface{}{
		(*Down_Kickoff)(nil),
		(*Down_Frame)(nil),
	}
}

func _Down_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Down)
	// m
	switch x := m.M.(type) {
	case *Down_Kickoff:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Kickoff); err != nil {
			return err
		}
	case *Down_Frame:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Frame); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Down.M has unexpected type %T", x)
	}
	return nil
}

func _Down_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Down)
	switch tag {
	case 1: // m.kickoff
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Down_DownKickOff)
		err := b.DecodeMessage(msg)
		m.M = &Down_Kickoff{msg}
		return true, err
	case 2: // m.frame
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Down_DownFrame)
		err := b.DecodeMessage(msg)
		m.M = &Down_Frame{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Down_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Down)
	// m
	switch x := m.M.(type) {
	case *Down_Kickoff:
		s := proto.Size(x.Kickoff)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Down_Frame:
		s := proto.Size(x.Frame)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Down_Snake struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Body                 []int32  `protobuf:"varint,2,rep,packed,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Down_Snake) Reset()         { *m = Down_Snake{} }
func (m *Down_Snake) String() string { return proto.CompactTextString(m) }
func (*Down_Snake) ProtoMessage()    {}
func (*Down_Snake) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_db5d93a88d7ba5ba, []int{1, 0}
}
func (m *Down_Snake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Down_Snake.Unmarshal(m, b)
}
func (m *Down_Snake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Down_Snake.Marshal(b, m, deterministic)
}
func (dst *Down_Snake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Down_Snake.Merge(dst, src)
}
func (m *Down_Snake) XXX_Size() int {
	return xxx_messageInfo_Down_Snake.Size(m)
}
func (m *Down_Snake) XXX_DiscardUnknown() {
	xxx_messageInfo_Down_Snake.DiscardUnknown(m)
}

var xxx_messageInfo_Down_Snake proto.InternalMessageInfo

func (m *Down_Snake) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *Down_Snake) GetBody() []int32 {
	if m != nil {
		return m.Body
	}
	return nil
}

type Down_DownKickOff struct {
	Cid                  int32         `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Foods                []int32       `protobuf:"varint,2,rep,packed,name=foods,proto3" json:"foods,omitempty"`
	Snakes               []*Down_Snake `protobuf:"bytes,3,rep,name=snakes,proto3" json:"snakes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Down_DownKickOff) Reset()         { *m = Down_DownKickOff{} }
func (m *Down_DownKickOff) String() string { return proto.CompactTextString(m) }
func (*Down_DownKickOff) ProtoMessage()    {}
func (*Down_DownKickOff) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_db5d93a88d7ba5ba, []int{1, 1}
}
func (m *Down_DownKickOff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Down_DownKickOff.Unmarshal(m, b)
}
func (m *Down_DownKickOff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Down_DownKickOff.Marshal(b, m, deterministic)
}
func (dst *Down_DownKickOff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Down_DownKickOff.Merge(dst, src)
}
func (m *Down_DownKickOff) XXX_Size() int {
	return xxx_messageInfo_Down_DownKickOff.Size(m)
}
func (m *Down_DownKickOff) XXX_DiscardUnknown() {
	xxx_messageInfo_Down_DownKickOff.DiscardUnknown(m)
}

var xxx_messageInfo_Down_DownKickOff proto.InternalMessageInfo

func (m *Down_DownKickOff) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *Down_DownKickOff) GetFoods() []int32 {
	if m != nil {
		return m.Foods
	}
	return nil
}

func (m *Down_DownKickOff) GetSnakes() []*Down_Snake {
	if m != nil {
		return m.Snakes
	}
	return nil
}

type Down_DownFrame struct {
	Foods                []int32  `protobuf:"varint,1,rep,packed,name=foods,proto3" json:"foods,omitempty"`
	Keycodes             []int32  `protobuf:"varint,2,rep,packed,name=keycodes,proto3" json:"keycodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Down_DownFrame) Reset()         { *m = Down_DownFrame{} }
func (m *Down_DownFrame) String() string { return proto.CompactTextString(m) }
func (*Down_DownFrame) ProtoMessage()    {}
func (*Down_DownFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_gosnake_db5d93a88d7ba5ba, []int{1, 2}
}
func (m *Down_DownFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Down_DownFrame.Unmarshal(m, b)
}
func (m *Down_DownFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Down_DownFrame.Marshal(b, m, deterministic)
}
func (dst *Down_DownFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Down_DownFrame.Merge(dst, src)
}
func (m *Down_DownFrame) XXX_Size() int {
	return xxx_messageInfo_Down_DownFrame.Size(m)
}
func (m *Down_DownFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_Down_DownFrame.DiscardUnknown(m)
}

var xxx_messageInfo_Down_DownFrame proto.InternalMessageInfo

func (m *Down_DownFrame) GetFoods() []int32 {
	if m != nil {
		return m.Foods
	}
	return nil
}

func (m *Down_DownFrame) GetKeycodes() []int32 {
	if m != nil {
		return m.Keycodes
	}
	return nil
}

func init() {
	proto.RegisterType((*Up)(nil), "comm.Up")
	proto.RegisterType((*Up_UpJoin)(nil), "comm.Up.UpJoin")
	proto.RegisterType((*Up_UpOp)(nil), "comm.Up.UpOp")
	proto.RegisterType((*Down)(nil), "comm.Down")
	proto.RegisterType((*Down_Snake)(nil), "comm.Down.Snake")
	proto.RegisterType((*Down_DownKickOff)(nil), "comm.Down.DownKickOff")
	proto.RegisterType((*Down_DownFrame)(nil), "comm.Down.DownFrame")
	proto.RegisterEnum("comm.Mode", Mode_name, Mode_value)
	proto.RegisterEnum("comm.KeyCode", KeyCode_name, KeyCode_value)
}

func init() { proto.RegisterFile("gosnake.proto", fileDescriptor_gosnake_db5d93a88d7ba5ba) }

var fileDescriptor_gosnake_db5d93a88d7ba5ba = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xb5, 0xd7, 0xeb, 0xa4, 0x9d, 0xa8, 0x74, 0x19, 0x02, 0x8a, 0x7c, 0x80, 0xa8, 0x12, 0xc2,
	0x2a, 0x34, 0x15, 0xee, 0x99, 0x4b, 0x69, 0x8b, 0x21, 0x90, 0x58, 0x4b, 0x23, 0x04, 0x97, 0xaa,
	0xb5, 0xd7, 0xc8, 0x58, 0xf6, 0x58, 0x09, 0x02, 0xe5, 0x9f, 0xf8, 0x04, 0x3e, 0x89, 0x7f, 0x00,
	0xed, 0x7a, 0xd3, 0x58, 0xa8, 0x3e, 0x58, 0xb3, 0xfb, 0xde, 0x9b, 0x37, 0x3b, 0x33, 0xb0, 0xf7,
	0x95, 0x56, 0xf5, 0x75, 0xa9, 0x26, 0xcd, 0x92, 0xbe, 0x13, 0xf2, 0x94, 0xaa, 0xea, 0xe0, 0x97,
	0x0b, 0x6c, 0xd1, 0xe0, 0x53, 0xe0, 0xdf, 0xa8, 0xa8, 0x47, 0xee, 0xd8, 0x0d, 0x07, 0xd1, 0xfe,
	0x44, 0x63, 0x93, 0x45, 0x33, 0x59, 0x34, 0xef, 0xa8, 0xa8, 0x63, 0x47, 0x1a, 0x18, 0x9f, 0x00,
	0xa3, 0x66, 0xc4, 0x0c, 0x69, 0xaf, 0x43, 0x9a, 0x37, 0xb1, 0x23, 0x19, 0x35, 0x41, 0x08, 0xbd,
	0x56, 0x82, 0x8f, 0x81, 0x57, 0x94, 0x29, 0x93, 0xf1, 0x5e, 0x04, 0x2d, 0xf9, 0x03, 0x65, 0x4a,
	0x9a, 0xfb, 0xe0, 0x18, 0xb8, 0xd6, 0xe1, 0x33, 0xe8, 0x97, 0x6a, 0x9d, 0x6e, 0xa9, 0x36, 0xef,
	0x54, 0xad, 0x5f, 0x6b, 0xf6, 0x06, 0x3d, 0xf5, 0xc0, 0xad, 0x0e, 0x7e, 0x33, 0xe0, 0x67, 0xf4,
	0xb3, 0xc6, 0x08, 0xfa, 0x65, 0x91, 0x96, 0x94, 0xe7, 0xb6, 0xe6, 0x47, 0xad, 0x4c, 0x83, 0xe6,
	0x37, 0x2d, 0xd2, 0x72, 0x9e, 0xe7, 0xb1, 0x23, 0x37, 0x44, 0x7c, 0x01, 0x7e, 0xbe, 0xbc, 0xae,
	0x94, 0x7d, 0xc0, 0xf0, 0x3f, 0xc5, 0x85, 0xc6, 0x62, 0x47, 0xb6, 0xa4, 0xe0, 0x08, 0xfc, 0x8f,
	0xba, 0x5d, 0x28, 0xc0, 0x4b, 0x8b, 0xcc, 0xd8, 0xf8, 0x52, 0x87, 0x88, 0xc0, 0x6f, 0x28, 0x5b,
	0x8f, 0xd8, 0xd8, 0x0b, 0x7d, 0x69, 0xe2, 0xe0, 0x0a, 0x06, 0x1d, 0xdb, 0x3b, 0x44, 0x43, 0xf0,
	0x73, 0xa2, 0x6c, 0x65, 0x55, 0xed, 0x01, 0x43, 0xe8, 0x99, 0xa1, 0xac, 0x46, 0xde, 0xd8, 0x0b,
	0x07, 0x91, 0xe8, 0x14, 0x65, 0xec, 0xa5, 0xc5, 0x83, 0x57, 0xb0, 0x7b, 0x5b, 0xe5, 0x36, 0x99,
	0xdb, 0x4d, 0x16, 0xc0, 0x8e, 0xed, 0xd6, 0xc6, 0xe5, 0xf6, 0x6c, 0xda, 0x77, 0xf8, 0x1c, 0xb8,
	0x1e, 0x01, 0xee, 0x00, 0x9f, 0x51, 0xad, 0x84, 0x83, 0x7d, 0xf0, 0x92, 0x97, 0x89, 0x70, 0x4d,
	0x10, 0x25, 0x82, 0x99, 0xe0, 0x24, 0x11, 0xde, 0xe1, 0x0c, 0xfa, 0x76, 0x08, 0x08, 0xd0, 0x9b,
	0xcd, 0xaf, 0xa6, 0xe7, 0x9f, 0x85, 0x83, 0xf7, 0x81, 0xbf, 0x3f, 0xbf, 0xb8, 0x14, 0x7f, 0x37,
	0x9f, 0x8b, 0xfb, 0xc0, 0x16, 0x89, 0xf8, 0xb3, 0xbd, 0xd8, 0x05, 0x5f, 0xbe, 0x7d, 0x13, 0x5f,
	0x0a, 0x57, 0x5b, 0x9d, 0xcd, 0x3f, 0xcd, 0xc4, 0xf0, 0xf4, 0xe1, 0x97, 0x07, 0x76, 0x03, 0x8f,
	0x56, 0x6a, 0xf9, 0x43, 0x2d, 0x8f, 0xf5, 0x53, 0x6f, 0x7a, 0x66, 0x1d, 0x4f, 0xfe, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x32, 0xd7, 0x92, 0x08, 0x9f, 0x02, 0x00, 0x00,
}
